package com.java.basics.exception;

public class ExceptionTest extends DeriveException {

	public static void main(String[] args) {

		/*try {
		    int c = 1/0;
		} catch (Exception e) {
		    System.out.println("E");
		} finally {
		    System.out.println("F");
		}*/
	
	
	
	Integer a = null;
	int b = a;
	System.out.println(b);

}
}
